# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
# This workflow will do a clean install of dotnet dependencies

name: Build and Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_test:
    name: Build and Test on dotnet ${{ matrix.dotnet-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: ['2.1.x']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Before Build
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Unit Test
      run: |
        dotnet test --no-build --verbosity normal src/IBM.Watson.Assistant.v1/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.Assistant.v2/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.CompareComply.v1/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.Discovery.v1/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.Discovery.v2/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.LanguageTranslator.v3/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.NaturalLanguageClassifier.v1/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.NaturalLanguageUnderstanding.v1/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.PersonalityInsights.v3/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.SpeechToText.v1/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.TextToSpeech.v1/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.ToneAnalyzer.v3/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.VisualRecognition.v3/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.VisualRecognition.v4/Test/Unit

    - name: Install Semantic Release and nuget dependencies
      run: |
        sudo apt-get install bumpversion
        npm install -g semantic-release
        npm install -g @semantic-release/changelog
        npm install -g @semantic-release/exec
        npm install -g @semantic-release/git
        npm install -g @semantic-release/github
        npm install -g @semantic-release/commit-analyzer
        npm install -g @semantic-release/release-notes-generator
        echo -e "\n\033[0;35mCommand: install Doxygen"
        sudo apt-get install doxygen

    - name: dotnet Pack to Nupkg
      run: |
        echo -e "\n\033[ 0;35mCommand: branchname must be APPVEYOR_REPO_TAG_NAME so building NuGet packages"
        dotnet pack src/IBM.Watson.Assistant.v1/IBM.Watson.Assistant.v1.csproj --configuration Release
        dotnet pack src/IBM.Watson.Assistant.v2/IBM.Watson.Assistant.v2.csproj --configuration Release
        dotnet pack src/IBM.Watson.CompareComply.v1/IBM.Watson.CompareComply.v1.csproj --configuration Release
        dotnet pack src/IBM.Watson.Discovery.v1/IBM.Watson.Discovery.v1.csproj --configuration Release
        dotnet pack src/IBM.Watson.Discovery.v2/IBM.Watson.Discovery.v2.csproj --configuration Release
        dotnet pack src/IBM.Watson.LanguageTranslator.v3/IBM.Watson.LanguageTranslator.v3.csproj --configuration Release
        dotnet pack src/IBM.Watson.NaturalLanguageClassifier.v1/IBM.Watson.NaturalLanguageClassifier.v1.csproj --configuration Release
        dotnet pack src/IBM.Watson.NaturalLanguageUnderstanding.v1/IBM.Watson.NaturalLanguageUnderstanding.v1.csproj --configuration Release
        dotnet pack src/IBM.Watson.PersonalityInsights.v3/IBM.Watson.PersonalityInsights.v3.csproj --configuration Release
        dotnet pack src/IBM.Watson.SpeechToText.v1/IBM.Watson.SpeechToText.v1.csproj --configuration Release
        dotnet pack src/IBM.Watson.TextToSpeech.v1/IBM.Watson.TextToSpeech.v1.csproj --configuration Release
        dotnet pack src/IBM.Watson.ToneAnalyzer.v3/IBM.Watson.ToneAnalyzer.v3.csproj --configuration Release
        dotnet pack src/IBM.Watson.VisualRecognition.v3/IBM.Watson.VisualRecognition.v3.csproj --configuration Release
        dotnet pack src/IBM.Watson.VisualRecognition.v4/IBM.Watson.VisualRecognition.v4.csproj --configuration Release

    - name: Publish to Nuget
      env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
          REPO_TAG_NAME: "5.2.1"
      run: |
        dotnet nuget push src/IBM.Watson.Assistant.v1/bin/Release/IBM.Watson.Assistant.v1.${REPO_TAG_NAME}.nupkg -k ${NUGET_TOKEN} -s https://api.nuget.org/v3/index.json
